name: Custeleportation
main: com.github.wincamxp.custeleportation.custeleportation
version: 1.1

commands:
  tp:
    description: Teleports one player to another.
    usage: /<command> <player> <player>