name: Custeleportation
main: com.github.wincamxp.custeleportation.custeleportation
version: 1.0

commands:
  tp:
    description: Teleports one player to another.
    usage: /<command> <player> <player>
    permission: cust.tp
    permission-message: You don't have node <permission>.
    
permissions:
  cust.tp:
    description: Allows usage of /tp
    default: op